### ISSUE TITLE
Generate correct integer types

### ISSUE THREAD

**Issue by kyleconroy** [kyleconroy/dinosql#39]
The Go types emitted for PostgreSQL columns with integer types are current incorrect. We should change them to the following:

* smallint -> int16
* integer -> int32
* bigint -> int64

https://www.postgresql.org/docs/current/datatype-numeric.html
https://www.postgresql.org/docs/current/datatype.html#DATATYPE-TABLE
https://golang.org/pkg/builtin/#int

**Comment by dom3k** [comment]
Hello @kyleconroy. Can you tell me why type int is wrong for type integer? 
Type int is at least 32 bits in size and type integer is 32 bits so it fits. It is all about optimization or something else? 

btw. Thank you for yours excellent work.

**Comment by frederikhors** [comment]
@kyleconroy I quote @dom3k:

> Can you tell me why type int is wrong for type integer?

Please.

**Comment by fr3fou** [comment]
> Hello @kyleconroy. Can you tell me why type int is wrong for type integer?
> Type int is at least 32 bits in size and type integer is 32 bits so it fits. It is all about optimization or something else?
> 
> btw. Thank you for yours excellent work.

I've been wondering the exact same thing, I'm afraid of overriding the types as there might be a reason for using `int32` that I don't know.
