### ISSUE TITLE
String arrays

### ISSUE THREAD

**Issue by kyleconroy** [kyleconroy/dinosql#7]
```sql
create table rooms (
            id varchar not null,
            members varchar[] not null default '{}'
);

-- name: GetMembersByRoom :one  
SELECT members
FROM rooms
WHERE id = $1;
```

**Comment by srenatus** [comment]
Just to clarify, the following issue is related to _this issue_, isn't it? ⬇️ 

Right now, dinosql will generate this code for me:
```go
const deleteToken = `-- name: DeleteToken :exec
DELETE FROM chef_authn_tokens cat
WHERE cat.id=$1
AND projects_match(cat.project_ids, $2::TEXT[])
`

type DeleteTokenParams struct {
        ID string
        ID string
}

func (q *Queries) DeleteToken(ctx context.Context, arg DeleteTokenParams) error {
        _, err := q.db.ExecContext(ctx, deleteToken, arg.ID, arg.ID)
        return err
}
```
In the SQL statement, `$2` is supposed to be an array, and the generate function should be something like
```go
type DeleteTokenParams struct {
        ID string
        Foo []string
}

func (q *Queries) DeleteToken(ctx context.Context, arg DeleteTokenParams) error {
        _, err := q.db.ExecContext(ctx, deleteToken, arg.ID, pq.Array(arg.Foo))
        return err
}
```

**Comment by kyleconroy** [comment]
@srenatus You are correct. To generate the correct method for the `DeleteToken` query, a few things need to be implemented:
- Support for the cast (`::`) operator
- Scanning into and from slices using `pq.Array`
- Generating the correct field name for the DeleteTokenParams struct

Once that's complete, your query should generate the following code:

```go
type DeleteTokenParams struct {
        ID string
        ProjectIDs []string
}

func (q *Queries) DeleteToken(ctx context.Context, arg DeleteTokenParams) error {
        _, err := q.db.ExecContext(ctx, deleteToken, arg.ID, pq.Array(arg.ProjectIDs))
        return err
}
```

Is the `projects_match` function a custom function? Or just a placeholder you're using?

**Comment by srenatus** [comment]
> Is the projects_match function a custom function? Or just a placeholder you're using?

Yup, it's a custom SQL function deployed with the schema. Would dinosql need to know about that?

**Comment by kyleconroy** [comment]
>  Would dinosql need to know about that?

In this specific case, no. DinoSQL will not validate calls to unknown functions. If the `$2` parameter did not include a cast, the parameter type would just be `interface{}`. It should probably error instead.
